# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tmux Super Fingers

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'tmux_super_fingers.tmux'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv

    - id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install python packages
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pipenv install --dev

    - name: Setup node.js (for pyright)
      uses: actions/setup-node@v1
      with:
        node-version: "16"

    - name: Install node packages
      run: yarn install

    - name: Run type checking
      run: pipenv run yarn run pyright

    - name: Lint
      run: pipenv run flake8

    - name: Test
      run: pipenv run pytest
